version: '3.9'

services:
  web:
    build: .
    command: ./run.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 8501:8501
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
