# fly.toml app configuration file generated for casestudytool on 2023-06-26T03:43:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "casestudytool"
primary_region = "jnb"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DJANGO_DEBUG = false

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    handlers = ["http"]
    port = "80"
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[[services]]
  protocol = "tcp"
  internal_port = 8501
  force_https = false

  [[services.ports]]
    handlers = ["http"]
    port = 8501


[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
