# fly.toml app configuration file generated for casestudytool-ml on 2023-06-26T14:09:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "casestudytool-ml"
primary_region = "jnb"
console_command = "/code/manage.py shell"

[env]
  PORT = "8501"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
