# Generated by Django 4.2 on 2023-06-17 09:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedMetric",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("explanation", models.CharField(max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="caselog",
            name="tracked_value",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=None, max_digits=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="caselog",
            name="tracked_description",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pages.trackedmetric",
            ),
        ),
    ]
