# Generated by Django 4.2 on 2023-06-10 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cases",
            new_name="Case",
        ),
    ]
