# Generated by Django 4.2 on 2023-06-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_caselog_pages_caselog_both_tracked_values_filled"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="caselog",
            name="pages_caselog_both_tracked_values_filled",
        ),
        migrations.AddConstraint(
            model_name="caselog",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("tracked_description__isnull", True),
                        ("tracked_value__isnull", True),
                    ),
                    models.Q(
                        ("tracked_description__isnull", False),
                        ("tracked_value__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="pages_caselog_both_tracked_values_filled",
            ),
        ),
    ]
