# Generated by Django 4.2 on 2023-06-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_caselog"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="description",
            field=models.CharField(default="DEscription", max_length=255),
            preserve_default=False,
        ),
    ]
